import { LOGO_PATH, LOGO_VIEWBOX } from './logoPaths'

// Brand mark: a faceted space sphere with a compass star and moon above it.
// Deliberately not a pentagon - the brief forbids five-sided shapes.
//
// This is inline SVG rather than an <img> for a reason that started as a bug
// report: browsers treat an <img> as a picture and will begin a native image
// drag from it, so the mark could be grabbed and dropped into the composer as
// an attachment. An <svg> element carries no drag handle at all, so the
// behaviour is gone rather than merely suppressed.
//
// One vector serves every size. There used to be a second, sphere-only asset
// for anything under 22px, because a 256px *raster* turns the compass star to
// noise when the browser scales it to 16. As a path it stays sharp, so that
// second asset is no longer earning its place.
//
// Geometry lives in ./logoPaths.ts, generated by `npm run vectorize` from
// public/pentagon-logo.png. See scripts/vectorize-logo.py.

// The raster this replaces capped out around 75% alpha over mid-grey ink,
// which read as roughly half-white against the app's black surface. Baking
// that into fillOpacity keeps the mark looking identical while letting it
// inherit the surrounding text colour.
const INK_OPACITY = 0.5

export function Logomark({ size = 18, className = '' }: { size?: number; className?: string }) {
  return (
    <svg
      viewBox={LOGO_VIEWBOX}
      width={size}
      height={size}
      role="presentation"
      aria-hidden="true"
      focusable="false"
      // No draggable={false} here, and that is the point: React's SVGProps has
      // no such property, because an <svg> root has no drag affordance to
      // disable. The .logo-mark rule in index.css covers selection and the
      // Safari-specific -webkit-user-drag.
      className={`logo-mark shrink-0 select-none ${className}`}
    >
      <path d={LOGO_PATH} fill="currentColor" fillOpacity={INK_OPACITY} fillRule="evenodd" />
    </svg>
  )
}

export function LogomarkBadge({
  size = 34,
  className = '',
  label,
}: {
  size?: number
  className?: string
  label?: string
}) {
  return (
    <span
      className={`grid shrink-0 place-items-center ${className}`}
      style={{ width: size, height: size }}
    >
      <Logomark size={size} className="opacity-90" />
      {label ? <span className="sr-only">{label}</span> : null}
    </span>
  )
}